General:
  #Supported languages: en_us, fi_fi (you can add more languages in the langs folder)
  Language: en_us
  UseMessages: false
  RequireEmptyHand: true
Permissions:
    Enabled: false
    UsingChairs: realchairs.use
Commands:
    Aliases:
    - "realchairs"
    - "rc"
    - "chairs"
    - "chair"
    Help:
      Argument: "help"
      Permission: "realchairs.help"
    Menu:
      Argument: "menu"
      Permission: "realchairs.menu"
    Add:
      Argument: "add"
      Permission: "realchairs.add"
    Remove:
      Argument: "remove"
      Permission: "realchairs.remove"
    List:
        Argument: "list"
        Permission: "realchairs.list"
    Reload:
        Argument: "reload"
        Permission: "realchairs.reload"
    Show:
        Argument: "show"
        Permission: "realchairs.show"
    Tool:
        Argument: "tool"
        Permission: "realchairs.tool"
    Height:
        Argument: "height"
        Permission: "realchairs.height"
        Disable: "disable"
    Clean:
        Argument: "clean"
        Permission: "realchairs.clean"
    Wipe:
        Argument: "wipe"
        Permission: "realchairs.wipe"
    Sit:
      Argument: "sit"
      Permission: "realchairs.sit"
      PermissionSelectHeight: "realchairs.sit.height"
Sounds:
  Sit:
    Enabled: true
    Sound: "minecraft:ui.toast.in"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
  Stand:
    Enabled: true
    Sound: "minecraft:ui.toast.out"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
  AddChair:
    Enabled: true
    Sound: "minecraft:entity.item_frame.add_item"
    Category: MASTER
    Pitch: 0.5
    Volume: 1
  RemoveChair:
    Enabled: true
    Sound: "minecraft:entity.item_frame.remove_item"
    Category: MASTER
    Pitch: 0.5
    Volume: 1
  Error:
    Enabled: true
    Sound: "minecraft:entity.villager.no"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
  Open:
    Enabled: true
    Sound: "minecraft:block.ender_chest.open"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
  Close:
    Enabled: true
    Sound: "minecraft:block.ender_chest.close"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
  Click:
    Enabled: true
    Sound: "minecraft:ui.button.click"
    Category: MASTER
    Pitch: 1.0
    Volume: 1
Effects:
  WhenSit:
    Enabled: false
    List:
      entry1:
        Type: REGENERATION
        Duration: 120
        Amplifier: 1
        Ambient: false
        Particles: false
        Icon: false
      entry2:
        Type: ABSORPTION
        Duration: 120
        Amplifier: 1
        Ambient: false
        Particles: false
        Icon: false
  WhenStand:
    Enabled: false
    List:
      entry1:
        Type: REGENERATION
        Duration: 120
        Amplifier: 1
        Ambient: false
        Particles: false
        Icon: false
      entry2:
        Type: ABSORPTION
        Duration: 120
        Amplifier: 1
        Ambient: false
        Particles: false
        Icon: false